#!/bin/sh
#
# Back up the entire system to LTO tape

# Tape device to use.  The device node names map to tape device
# modes as defined in /etc/stinit.def.  There are 4 modes in
# stinit and they map to device notes like this:
#
#     mode 1      /dev/st0
#     mode 2      /dev/st0l
#     mode 3      /dev/st0m
#     mode 4      /dev/st0a
#
# The letters don't really make sense, but that's what they are.
TAPEDEV="/dev/st0l"

# Total tape size in gigabytes.  Be sure to match the size to the mode
# in use, which may call for a 2:1 compression reporting.
TOTAL_SIZE="1600"

# Directories to include
INCLUDE="/etc /root /home /usr/local"

# File listing exclude patterns for tar (optional)
EXCLUDE="excludes.txt"

# Common variables
PATH=/bin:/usr/bin:/sbin:/usr/sbin
PROG="$(basename $0)"
TMPDIR="$(mktemp -d -p /var/tmp -t ${PROG}.XXXXXX)"
trap 'rm -rf "${TMPDIR}"' EXIT

# Initialize the tape drive
sudo stinit

# DR_OPEN means there is no tape loaded
# If we see that, just exit.
sudo mt -f ${TAPEDEV} status | tail -n 1 | grep -q DR_OPEN >/dev/null 2>&1

if [ $? -eq 0 ]; then
    echo "Insert a tape in the drive and try again."
    exit 0
fi

# Rewind just in case
sudo mt -f ${TAPEDEV} rewind

# NOTE:  This is a long erase and will run for hours.
#sudo mt -f $TAPEDEV erase

# Perform a short erase
sudo dd if=/dev/zero of=${TAPEDEV} bs=512 count=1
sudo mt -f ${TAPEDEV} rewind

# Actually use tar to write to a tape drive
EXCLUDE_OPT=

if [ -f "${EXCLUDE}" ]; then
    EXCLUDE_OPT="-X ${EXCLUDE}"
fi

sudo tar -c -v -f ${TAPEDEV} --totals ${EXCLUDE_OPT} ${INCLUDE} 2>&1 | tee ${TMPDIR}/tar.log
sudo mt -f ${TAPEDEV} rewind
sudo mt -f ${TAPEDEV} eject

# Report backup size
SIZE_WRITTEN=$(grep "^Total bytes written:" ${TMPDIR}/tar.log | rev | cut -d ' ' -f 1 | rev | awk '{ printf "%.2f", $1/1024/1024/1024; }')
REMAINING="$(echo "scale=2; ((${TOTAL_SIZE}-${SIZE_WRITTEN})/${TOTAL_SIZE})*100.00" | bc)"
echo "${SIZE_WRITTEN} GB written to tape."
echo "You still have ${REMAINING}% of a backup tape remaining."
